In [82]:
import pandas as pd

file_path = r'D:\PFE_M2\ocr_results\text_frame.csv'
df = pd.read_csv(file_path)
df

,frame,text_of_frame,username,servername
0,frame_0.png,is\n,inconnu,inconnu
1,frame_1.png,Avertissement de connexion\n\nCe sytéme inform...,inconnu,inconnu
2,frame_2.png,"»\n~ ~e\nhe By,\n ...",inconnu,inconnu
3,frame_3.png,Multi-Factor Authentication\nEnter the MFA cod...,inconnu,inconnu
4,frame_4.png,Multi-Factor Authentication\nEnter the MFA cod...,inconnu,inconnu
...,...,...,...,...
542,frame_542.png,Oracle Database 11g Enterprise Edition Release...,oracle,OV-BSCSR4PROD-BD
543,frame_543.png,Oracle Database 11g Enterprise Edition Release...,oracle,OV-BSCSR4PROD-BD
544,frame_544.png,Oracle Database 11g Enterprise Edition Release...,oracle,OV-BSCSR4PROD-BD
545,frame_545.png,Oracle Database 11g Enterprise Edition Release...,oracle,OV-BSCSR4PROD-BD
546,frame_546.png,Oracle Database 11g Enterprise Edition Release...,oracle,OV-BSCSR4PROD-BD

In [83]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 547 entries, 0 to 546
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   frame          547 non-null    object
 1   text_of_frame  547 non-null    object
 2   username       547 non-null    object
 3   servername     547 non-null    object
dtypes: object(4)
memory usage: 17.2+ KB

#### Voir les frames doublons

In [85]:
import pandas as pd

# Suppose que df est déjà défini
cols_to_check = ['text_of_frame', 'username', 'servername']

# 1. Trouver les lignes dupliquées (hors colonne 'frame')
duplicated_mask = df.duplicated(subset=cols_to_check, keep=False)
duplicates_df = df[duplicated_mask].copy()

# 2. Grouper les frames identiques
grouped = (
    duplicates_df
    .groupby(cols_to_check)['frame']
    .apply(list)
    .reset_index()
)

# 3. Construire un seul message par groupe (en gardant le premier frame comme référence)
result = []
total_doublons = 0

for frames in grouped['frame']:
    if len(frames) > 1:
        first = frames[0]
        rest = frames[1:]
        result.append(f"Le frame {first} a pour doublons les frames {rest}")
        total_doublons += len(rest)  # Ne compter que les doublons, pas la première apparition

# 4. Affichage
for ligne in result:
    print(ligne)

# 5. Affichage du total
print(f"\nNombre total de doublons : {total_doublons}")

Le frame frame_73.png a pour doublons les frames ['frame_74.png']
Le frame frame_136.png a pour doublons les frames ['frame_137.png']
Le frame frame_160.png a pour doublons les frames ['frame_161.png', 'frame_162.png', 'frame_163.png', 'frame_164.png', 'frame_165.png', 'frame_166.png', 'frame_167.png', 'frame_168.png', 'frame_169.png', 'frame_170.png', 'frame_171.png', 'frame_172.png', 'frame_173.png', 'frame_174.png', 'frame_175.png', 'frame_176.png', 'frame_177.png', 'frame_178.png', 'frame_179.png', 'frame_180.png', 'frame_181.png', 'frame_182.png', 'frame_183.png', 'frame_184.png', 'frame_185.png', 'frame_186.png', 'frame_187.png', 'frame_188.png', 'frame_189.png', 'frame_190.png', 'frame_191.png', 'frame_192.png', 'frame_193.png', 'frame_194.png', 'frame_195.png', 'frame_196.png', 'frame_197.png', 'frame_198.png', 'frame_199.png', 'frame_200.png', 'frame_201.png', 'frame_202.png', 'frame_203.png', 'frame_204.png', 'frame_205.png', 'frame_206.png', 'frame_207.png', 'frame_208.png', 'frame_209.png', 'frame_210.png', 'frame_211.png', 'frame_212.png', 'frame_213.png', 'frame_214.png', 'frame_215.png', 'frame_216.png', 'frame_217.png', 'frame_218.png', 'frame_219.png', 'frame_220.png', 'frame_221.png', 'frame_222.png', 'frame_223.png', 'frame_224.png', 'frame_225.png', 'frame_226.png', 'frame_227.png', 'frame_228.png', 'frame_229.png', 'frame_230.png', 'frame_231.png', 'frame_232.png', 'frame_233.png', 'frame_234.png', 'frame_235.png', 'frame_236.png', 'frame_237.png', 'frame_238.png', 'frame_239.png', 'frame_240.png', 'frame_241.png', 'frame_242.png', 'frame_243.png', 'frame_244.png', 'frame_245.png', 'frame_246.png', 'frame_247.png', 'frame_248.png', 'frame_249.png', 'frame_250.png', 'frame_251.png', 'frame_252.png', 'frame_253.png', 'frame_254.png', 'frame_255.png', 'frame_256.png', 'frame_257.png', 'frame_258.png', 'frame_259.png', 'frame_260.png', 'frame_261.png', 'frame_262.png', 'frame_263.png', 'frame_264.png', 'frame_265.png', 'frame_266.png', 'frame_267.png', 'frame_268.png', 'frame_269.png', 'frame_270.png', 'frame_271.png', 'frame_272.png', 'frame_273.png', 'frame_274.png', 'frame_275.png', 'frame_276.png', 'frame_277.png', 'frame_278.png', 'frame_279.png', 'frame_280.png', 'frame_281.png', 'frame_282.png', 'frame_283.png', 'frame_284.png', 'frame_285.png', 'frame_286.png', 'frame_287.png', 'frame_288.png', 'frame_289.png', 'frame_290.png', 'frame_291.png', 'frame_292.png', 'frame_293.png', 'frame_294.png', 'frame_295.png', 'frame_296.png', 'frame_297.png', 'frame_298.png', 'frame_299.png', 'frame_300.png', 'frame_301.png', 'frame_302.png', 'frame_303.png', 'frame_304.png', 'frame_305.png', 'frame_306.png', 'frame_307.png', 'frame_308.png', 'frame_309.png', 'frame_310.png', 'frame_311.png', 'frame_312.png', 'frame_313.png', 'frame_314.png', 'frame_315.png', 'frame_316.png', 'frame_317.png', 'frame_318.png', 'frame_319.png', 'frame_320.png', 'frame_321.png', 'frame_322.png', 'frame_323.png', 'frame_324.png', 'frame_325.png', 'frame_326.png', 'frame_327.png', 'frame_328.png', 'frame_329.png', 'frame_330.png', 'frame_331.png', 'frame_332.png', 'frame_333.png', 'frame_334.png', 'frame_335.png', 'frame_336.png', 'frame_337.png', 'frame_338.png', 'frame_339.png', 'frame_340.png', 'frame_341.png', 'frame_342.png', 'frame_343.png', 'frame_344.png', 'frame_345.png', 'frame_346.png', 'frame_347.png', 'frame_348.png', 'frame_349.png', 'frame_350.png', 'frame_351.png', 'frame_352.png', 'frame_353.png', 'frame_354.png', 'frame_355.png', 'frame_356.png', 'frame_357.png', 'frame_358.png', 'frame_359.png', 'frame_360.png', 'frame_361.png', 'frame_362.png', 'frame_363.png', 'frame_364.png', 'frame_365.png', 'frame_366.png', 'frame_367.png', 'frame_368.png', 'frame_369.png', 'frame_370.png', 'frame_371.png', 'frame_372.png', 'frame_373.png', 'frame_374.png', 'frame_375.png', 'frame_376.png', 'frame_377.png', 'frame_378.png', 'frame_379.png', 'frame_380.png', 'frame_381.png', 'frame_382.png', 'frame_383.png', 'frame_384.png', 'frame_385.png', 'frame_386.png', 'frame_387.png', 'frame_388.png', 'frame_389.png', 'frame_390.png', 'frame_391.png', 'frame_392.png', 'frame_393.png', 'frame_394.png', 'frame_395.png', 'frame_396.png', 'frame_397.png', 'frame_398.png', 'frame_399.png', 'frame_400.png', 'frame_401.png', 'frame_402.png', 'frame_403.png', 'frame_404.png', 'frame_405.png', 'frame_406.png', 'frame_407.png', 'frame_408.png', 'frame_409.png', 'frame_410.png', 'frame_411.png', 'frame_412.png', 'frame_413.png', 'frame_414.png', 'frame_415.png', 'frame_416.png', 'frame_417.png', 'frame_418.png', 'frame_419.png', 'frame_420.png', 'frame_421.png', 'frame_422.png', 'frame_423.png', 'frame_424.png', 'frame_425.png', 'frame_426.png', 'frame_427.png', 'frame_428.png', 'frame_429.png', 'frame_430.png', 'frame_431.png', 'frame_432.png', 'frame_433.png', 'frame_434.png', 'frame_435.png', 'frame_436.png', 'frame_437.png', 'frame_438.png', 'frame_439.png', 'frame_440.png', 'frame_441.png', 'frame_442.png', 'frame_443.png', 'frame_444.png', 'frame_445.png', 'frame_446.png', 'frame_447.png', 'frame_448.png', 'frame_449.png', 'frame_450.png', 'frame_451.png', 'frame_452.png', 'frame_453.png', 'frame_454.png', 'frame_455.png', 'frame_456.png', 'frame_457.png', 'frame_458.png', 'frame_459.png', 'frame_460.png', 'frame_461.png', 'frame_462.png', 'frame_463.png', 'frame_464.png', 'frame_465.png', 'frame_466.png', 'frame_467.png', 'frame_468.png', 'frame_469.png', 'frame_470.png', 'frame_471.png', 'frame_472.png', 'frame_473.png', 'frame_474.png', 'frame_475.png', 'frame_476.png', 'frame_477.png', 'frame_478.png', 'frame_479.png', 'frame_480.png', 'frame_481.png', 'frame_482.png', 'frame_483.png', 'frame_484.png', 'frame_485.png', 'frame_486.png', 'frame_487.png', 'frame_488.png', 'frame_489.png', 'frame_490.png', 'frame_491.png', 'frame_492.png', 'frame_493.png', 'frame_494.png', 'frame_495.png', 'frame_496.png', 'frame_497.png', 'frame_498.png', 'frame_499.png', 'frame_500.png', 'frame_501.png', 'frame_502.png', 'frame_503.png', 'frame_504.png', 'frame_505.png', 'frame_506.png', 'frame_507.png', 'frame_508.png', 'frame_509.png', 'frame_510.png', 'frame_511.png', 'frame_512.png', 'frame_513.png', 'frame_514.png', 'frame_515.png', 'frame_516.png', 'frame_517.png', 'frame_518.png', 'frame_519.png', 'frame_520.png', 'frame_521.png', 'frame_522.png', 'frame_523.png', 'frame_524.png', 'frame_525.png', 'frame_526.png', 'frame_527.png', 'frame_528.png', 'frame_529.png', 'frame_530.png', 'frame_531.png', 'frame_532.png', 'frame_533.png', 'frame_534.png', 'frame_535.png', 'frame_536.png', 'frame_537.png', 'frame_538.png', 'frame_539.png', 'frame_540.png', 'frame_541.png', 'frame_542.png', 'frame_543.png', 'frame_544.png', 'frame_545.png', 'frame_546.png']
Le frame frame_154.png a pour doublons les frames ['frame_155.png', 'frame_156.png', 'frame_157.png', 'frame_158.png', 'frame_159.png']
Le frame frame_142.png a pour doublons les frames ['frame_143.png', 'frame_144.png', 'frame_145.png', 'frame_146.png', 'frame_147.png', 'frame_148.png']
Le frame frame_134.png a pour doublons les frames ['frame_135.png']
Le frame frame_56.png a pour doublons les frames ['frame_57.png']
Le frame frame_34.png a pour doublons les frames ['frame_35.png', 'frame_36.png', 'frame_37.png', 'frame_38.png', 'frame_39.png']
Le frame frame_41.png a pour doublons les frames ['frame_42.png']
Le frame frame_30.png a pour doublons les frames ['frame_32.png']
Le frame frame_43.png a pour doublons les frames ['frame_44.png', 'frame_45.png']
Le frame frame_128.png a pour doublons les frames ['frame_129.png']
Le frame frame_108.png a pour doublons les frames ['frame_109.png']
Le frame frame_110.png a pour doublons les frames ['frame_111.png', 'frame_112.png']

Nombre total de doublons : 414

#### Supprimer les doublons

In [87]:
import pandas as pd

# Suppose que df est déjà chargé
cols_to_check = ['text_of_frame', 'username', 'servername']

# Étape 1 : Marquer les doublons — True pour les lignes répétées après la première
duplicated_mask = df.duplicated(subset=cols_to_check, keep='first')

# Étape 2 : Conserver uniquement les premières occurrences
df_cleaned = df[~duplicated_mask].copy()

# Étape 3 : Réinitialiser les index si besoin et trier selon l’ordre d’origine
df_cleaned = df_cleaned.sort_values(by='frame', key=lambda col: col.str.extract(r'(\d+)').astype(int)[0])

In [88]:
df_cleaned

,frame,text_of_frame,username,servername
0,frame_0.png,is\n,inconnu,inconnu
1,frame_1.png,Avertissement de connexion\n\nCe sytéme inform...,inconnu,inconnu
2,frame_2.png,"»\n~ ~e\nhe By,\n ...",inconnu,inconnu
3,frame_3.png,Multi-Factor Authentication\nEnter the MFA cod...,inconnu,inconnu
4,frame_4.png,Multi-Factor Authentication\nEnter the MFA cod...,inconnu,inconnu
...,...,...,...,...
151,frame_151.png,Oracle Database 11g Enterprise Edition Release...,oracle,OV-BSCSR4PROD-BD
152,frame_152.png,Oracle Database 11g Enterprise Edition Release...,oracle,OV-BSCSR4PROD-BD
153,frame_153.png,Oracle Database 11g Enterprise Edition Release...,oracle,OV-BSCSR4PROD-BD
154,frame_154.png,Oracle Database 11g Enterprise Edition Release...,oracle,OV-BSCSR4PROD-BD
160,frame_160.png,Oracle Database 11g Enterprise Edition Release...,oracle,OV-BSCSR4PROD-BD

In [89]:
# Vérification : y a-t-il encore des doublons dans df_cleaned ?
nb_doublons_restants = df_cleaned.duplicated(subset=cols_to_check, keep=False).sum()

print(f"Nombre de doublons restants dans df_cleaned : {nb_doublons_restants}")

Nombre de doublons restants dans df_cleaned : 0

### **Phase 4 : Extraction de commandes systèmes et SQL sur chaque frame**

In [91]:
import re
import pandas as pd

# === Prompts
SQL_PROMPTS = [
    r"SQL>",                 # Oracle
    r"[a-zA-Z0-9_\-]+=#",    # PostgreSQL superuser
    r"[a-zA-Z0-9_\-]+=>",    # PostgreSQL normal user
]
SQL_PROMPT_REGEX = re.compile(rf"^({'|'.join(SQL_PROMPTS)})\s*(.*)", re.IGNORECASE)
SYSTEM_PROMPT_REGEX = re.compile(r"\[([^\s@]+)@([^\s\]]+)\s~\](\$|#)")

SQL_SIMPLE_COMMANDS = {"exit", "quit", "connect", "conn", "disconnect", "disc", r"\q"}


def extract_commands_with_type(text):
    if not isinstance(text, str):
        return []

    lines = text.splitlines()
    commands = []

    current_cmd = ""
    inside_sql = False

    for line in lines:
        line = line.rstrip()

        # === SYSTEM PROMPT
        sys_match = SYSTEM_PROMPT_REGEX.match(line)
        if sys_match:
            # Annuler toute commande SQL en cours (si elle n'est pas terminée par ;)
            if inside_sql:
                current_cmd = ""
                inside_sql = False

            cmd = line[sys_match.end():].strip()
            if cmd:
                commands.append((cmd, "sys"))
            continue

        # === SQL PROMPT
        sql_match = SQL_PROMPT_REGEX.match(line)
        if sql_match:
            # Si on était en train d’accumuler une commande SQL et qu’elle n’était pas terminée → on l’abandonne
            if inside_sql:
                current_cmd = ""
                inside_sql = False

            sql_line = sql_match.group(2).strip()

            # Si la commande est simple (exit, etc.) → extraire immédiatement
            if sql_line.lower().rstrip(";") in SQL_SIMPLE_COMMANDS:
                commands.append((sql_line, "sql"))
                continue

            # Démarrer une nouvelle commande SQL multi-ligne
            current_cmd = sql_line + "\n"
            inside_sql = True
            continue

        # === Accumuler lignes SQL jusqu’à trouver un ;
        if inside_sql:
            current_cmd += line.strip() + "\n"
            if line.strip().endswith(";"):
                commands.append((current_cmd.strip(), "sql"))
                current_cmd = ""
                inside_sql = False
            continue

        # === Autres lignes ignorées (hors SQL ou système)
        continue

    # On ne garde pas de commande SQL non terminée par ;
    return commands


# === Application sur df_cleaned avec duplication dynamique
def enrich_df_with_commands(df):
    all_rows = []

    for _, row in df.iterrows():
        command_tuples = extract_commands_with_type(row['text_of_frame'])

        if not command_tuples:
            continue

        historique_cmd = '\n\n'.join(cmd for cmd, _ in command_tuples)

        for cmd, cmd_type in command_tuples:
            new_row = row.copy()
            new_row['historique_cmd'] = historique_cmd
            new_row['cmd_sys'] = cmd if cmd_type == "sys" else ""
            new_row['cmd_sql'] = cmd if cmd_type == "sql" else ""
            all_rows.append(new_row)

    return pd.DataFrame(all_rows)


# === Exécution
df_cleaned = enrich_df_with_commands(df_cleaned)

In [92]:
df_cleaned

,frame,text_of_frame,username,servername,historique_cmd,cmd_sys,cmd_sql
6,frame_6.png,[oracle@OV-BSCSR4PROD-BD ~]$ df -h\nSys. de fi...,oracle,OV-BSCSR4PROD-BD,df -h\n\n. oraenv\n\n. oraenv ...,df -h,
6,frame_6.png,[oracle@OV-BSCSR4PROD-BD ~]$ df -h\nSys. de fi...,oracle,OV-BSCSR4PROD-BD,df -h\n\n. oraenv\n\n. oraenv ...,. oraenv,
6,frame_6.png,[oracle@OV-BSCSR4PROD-BD ~]$ df -h\nSys. de fi...,oracle,OV-BSCSR4PROD-BD,df -h\n\n. oraenv\n\n. oraenv ...,. oraenv ...,
6,frame_6.png,[oracle@OV-BSCSR4PROD-BD ~]$ df -h\nSys. de fi...,oracle,OV-BSCSR4PROD-BD,df -h\n\n. oraenv\n\n. oraenv ...,sqlp,
7,frame_7.png,[oracle@OV-BSCSR4PROD-BD ~]$ df -h\nSys. de fi...,oracle,OV-BSCSR4PROD-BD,df -h\n\n. oraenv\n\n. oraenv\n\nsqlp,df -h,
...,...,...,...,...,...,...,...
154,frame_154.png,Oracle Database 11g Enterprise Edition Release...,oracle,OV-BSCSR4PROD-BD,exit\n\n. oraenv\n\nsqlp,. oraenv,
154,frame_154.png,Oracle Database 11g Enterprise Edition Release...,oracle,OV-BSCSR4PROD-BD,exit\n\n. oraenv\n\nsqlp,sqlp,
160,frame_160.png,Oracle Database 11g Enterprise Edition Release...,oracle,OV-BSCSR4PROD-BD,exit\n\n. oraenv\n\nsqlp,,exit
160,frame_160.png,Oracle Database 11g Enterprise Edition Release...,oracle,OV-BSCSR4PROD-BD,exit\n\n. oraenv\n\nsqlp,. oraenv,
160,frame_160.png,Oracle Database 11g Enterprise Edition Release...,oracle,OV-BSCSR4PROD-BD,exit\n\n. oraenv\n\nsqlp,sqlp,

In [93]:
print(df_cleaned['servername'].unique())

print(df_cleaned['username'].unique())

['OV-BSCSR4PROD-BD' 'ov-cspprod' 'OV-IDENT-BD' 'OV-GAIAPROD-BD'
 'OV-RCU-BD' 'OK-DWH-BD' 'OV-CSP_PRADA-BD' 'ov-smile-bd' 'ov-w4-bd'
 'OV-GEOMAP-BD' 'OV-GIRAFE-BD' 'OV-MMG-BD' 'OV-JDEPROD-BD']
['oracle']

In [94]:
with open(r"D:\PFE_M2\output\commandes_sys.txt", "w", encoding="utf-8") as f:
    for cmd in df_cleaned["cmd_sys"]:
        if isinstance(cmd, str) and cmd.strip():  # ignorer NaN, "", "   "
            f.write(cmd.strip() + "\n\n")

In [95]:
with open(r"D:\PFE_M2\output\commandes_sql.txt", "w", encoding="utf-8") as f:
    for cmd in df_cleaned["cmd_sql"]:
        if isinstance(cmd, str) and cmd.strip():  # ignorer NaN, "", "   "
            f.write(cmd.strip() + "\n\n")

In [112]:
import os

# Définir le chemin de destination
output_path = r'D:\PFE_M2\output\data_cmd_session.csv'

# Sauvegarder le DataFrame
df_cleaned.to_csv(output_path, index=False)

print(f"DataFrame enregistré à : {output_path}")

DataFrame enregistré à : D:\PFE_M2\output\data_cmd_session.csv